"""Capabilities data - moved to new structure for alignment.

This is the source of truth now.
Legacy aiw_workspace/capability_registry re-exports from here.
"""

def _capabilities_db() -> list[dict]:
    return [
        {
            "name": "file_read",
            "kind": "tool",
            "status": "available",
            "risk": "low",
            "description": "Reads the content of a file up to a size limit.",
            "requires_confirmation": False,
            "allows_external_io": False,
            "writes_files": False,
            "runs_code": False,
            "network_access": False,
            "modifies_git": False,
            "reads_secrets": False,
            "artifacts_path": ".aiw/tools/file_read",
            "input_schema": {"path": "string", "max_bytes": "integer"},
            "blocked_by_default": False,
            "allowed_modes": ["dry_run", "manual", "auto"],
            "source": "aiw_runtime.tools"
        },
        {
            "name": "codeact_sandbox",
            "kind": "action",
            "status": "experimental",
            "risk": "high",
            "description": "Runs confirmed Python snippets in a local best-effort host sandbox with evidence artifacts.",
            "requires_confirmation": True,
            "allows_external_io": False,
            "writes_files": True,
            "runs_code": True,
            "network_access": False,
            "modifies_git": False,
            "reads_secrets": False,
            "artifacts_path": ".aiw/workspaces/<workspace_id>/codeact/runs/<run_id>",
            "input_schema": {
                "kind": "python_eval",
                "title": "string",
                "code": "string",
                "timeout_seconds": "integer",
                "max_stdout_chars": "integer",
                "max_stderr_chars": "integer"
            },
            "blocked_by_default": True,
            "allowed_modes": ["manual"],
            "source": "aiw.providers.execution.codeact_sandbox (migrado)"
        },
        {
            "name": "file_write",
            "kind": "tool",
            "status": "available",
            "risk": "medium",
            "description": "Writes or overwrites content to a file.",
            "requires_confirmation": True,
            "allows_external_io": False,
            "writes_files": True,
            "runs_code": False,
            "network_access": False,
            "modifies_git": False,
            "reads_secrets": False,
            "artifacts_path": ".aiw/tools/file_write",
            "input_schema": {"path": "string", "content": "string", "overwrite": "boolean"},
            "blocked_by_default": False,
            "allowed_modes": ["manual", "auto"],
            "source": "aiw_runtime.tools"
        },
        {
            "name": "file_patch",
            "kind": "tool",
            "status": "available",
            "risk": "medium",
            "description": "Replaces specific strings within a file.",
            "requires_confirmation": True,
            "allows_external_io": False,
            "writes_files": True,
            "runs_code": False,
            "network_access": False,
            "modifies_git": False,
            "reads_secrets": False,
            "artifacts_path": ".aiw/tools/file_patch",
            "input_schema": {"path": "string", "old_text": "string", "new_text": "string", "expected_replacements": "integer"},
            "blocked_by_default": False,
            "allowed_modes": ["manual", "auto"],
            "source": "aiw_runtime.tools"
        },
        {
            "name": "shell_exec",
            "kind": "tool",
            "status": "available",
            "risk": "high",
            "description": "Executes shell commands in a constrained environment.",
            "requires_confirmation": True,
            "allows_external_io": True,
            "writes_files": True,
            "runs_code": True,
            "network_access": False,
            "modifies_git": False,
            "reads_secrets": False,
            "artifacts_path": ".aiw/tools/shell_exec",
            "input_schema": {"command": "string", "timeout": "integer"},
            "blocked_by_default": False,
            "allowed_modes": ["manual", "auto"],
            "source": "aiw_runtime.tools"
        },
        {
            "name": "project_patch_preview",
            "kind": "tool",
            "status": "available",
            "risk": "medium",
            "description": "Previews a change without applying it to the project directly.",
            "requires_confirmation": False,
            "allows_external_io": False,
            "writes_files": True,
            "runs_code": False,
            "network_access": False,
            "modifies_git": False,
            "reads_secrets": False,
            "artifacts_path": ".aiw/patches",
            "input_schema": {"path": "string", "old_text": "string", "new_text": "string", "expected_replacements": "integer", "reason": "string"},
            "blocked_by_default": False,
            "allowed_modes": ["dry_run", "manual", "auto"],
            "source": "aiw_runtime.tools"
        },
        # Round 2 - 6. Mais tools
        {
            "name": "web_search",
            "kind": "tool",
            "status": "available",
            "risk": "medium",
            "description": "Web search for external context (stub in v1; real via provider later).",
            "requires_confirmation": False,
            "allows_external_io": True,
            "writes_files": False,
            "runs_code": False,
            "network_access": True,
            "modifies_git": False,
            "reads_secrets": False,
            "artifacts_path": ".aiw/tools/web_search",
            "input_schema": {"query": "string", "max_results": "integer"},
            "blocked_by_default": False,
            "allowed_modes": ["dry_run", "manual"],
            "source": "aiw.providers.context + tools"
        },
        {
            "name": "git_log",
            "kind": "tool",
            "status": "available",
            "risk": "low",
            "description": "Read git history / log for context.",
            "requires_confirmation": False,
            "allows_external_io": False,
            "writes_files": False,
            "runs_code": False,
            "network_access": False,
            "modifies_git": True,
            "reads_secrets": False,
            "artifacts_path": ".aiw/tools/git",
            "input_schema": {"path": "string", "max_entries": "integer"},
            "blocked_by_default": False,
            "allowed_modes": ["dry_run", "manual", "auto"],
            "source": "aiw_runtime.tools"
        },
        {
            "name": "git_diff",
            "kind": "tool",
            "status": "available",
            "risk": "low",
            "description": "Show git diff for workspace or specific paths.",
            "requires_confirmation": False,
            "allows_external_io": False,
            "writes_files": False,
            "runs_code": False,
            "network_access": False,
            "modifies_git": True,
            "reads_secrets": False,
            "artifacts_path": ".aiw/tools/git",
            "input_schema": {"ref_a": "string", "ref_b": "string"},
            "blocked_by_default": False,
            "allowed_modes": ["dry_run", "manual", "auto"],
            "source": "aiw_runtime.tools"
        },
    ]
