"""Workspace profile resolution for AIW."""

from .profiles import (
    DEFAULT_WORKSPACE,
    load_workspaces_config,
    normalize_workspace_id,
    resolve_workspace,
    execution_policy,
    validate_workspace_path,
    detect_stack,
    validate_profile,
    validate_test_command,
    add_workspace,
    remove_workspace,
)
from .test_runner import (
    tests_payload,
    preview_test_command,
    run_test_command,
    list_test_runs,
    list_all_test_runs,
    get_test_run,
    rerun_test_run,
    load_patch_preview,
    suggest_tests_for_patch,
    preview_patch_suggested_test,
    run_patch_suggested_test,
)
from .validation_plan import (
    validation_plan_for_patch,
    ensure_validation_plan_snapshot,
    list_validation_plan_snapshots,
    get_validation_plan_snapshot,
    compare_validation_plan_snapshots,
    validation_reliability,
    preview_validation_plan_command,
    run_validation_plan_commands,
)
from .patch_gate import (
    review_gate_for_patch,
    list_review_gates,
    apply_reviewed_patch,
)
from .test_coverage_intent import analyze_test_coverage_intent
from .coverage_report import analyze_patch_coverage
from .coverage_baseline import get_current_coverage_baseline, promote_coverage_baseline, list_coverage_baselines, coverage_diff

__all__ = [
    "DEFAULT_WORKSPACE",
    "load_workspaces_config",
    "normalize_workspace_id",
    "resolve_workspace",
    "execution_policy",
    "validate_workspace_path",
    "detect_stack",
    "validate_profile",
    "validate_test_command",
    "add_workspace",
    "remove_workspace",
    "tests_payload",
    "preview_test_command",
    "run_test_command",
    "list_test_runs",
    "list_all_test_runs",
    "get_test_run",
    "rerun_test_run",
    "load_patch_preview",
    "suggest_tests_for_patch",
    "preview_patch_suggested_test",
    "run_patch_suggested_test",
    "validation_plan_for_patch",
    "ensure_validation_plan_snapshot",
    "list_validation_plan_snapshots",
    "get_validation_plan_snapshot",
    "compare_validation_plan_snapshots",
    "validation_reliability",
    "preview_validation_plan_command",
    "run_validation_plan_commands",
    "review_gate_for_patch",
    "list_review_gates",
    "apply_reviewed_patch",
    "analyze_test_coverage_intent",
    "analyze_patch_coverage",
    "get_current_coverage_baseline",
    "promote_coverage_baseline",
    "list_coverage_baselines",
    "coverage_diff",
]
